version: "3.7"
services:

  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./broker-config:/mosquitto/config:rw
      - ./broker-data:/mosquitto/data:rw
      - ./broker-log:/mosquitto/log:rw
    networks:
      - mqtt5-network

  # InfluxDB
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086" # InfluxDB API port
    environment:
      - INFLUXDB_DB=smarthome
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin_password
    volumes:
      - ./influxdb/data:/var/lib/influxdb:rw
    networks:
      - mqtt5-network

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:
  influxdb:

networks:
  mqtt5-network:
    name: mqtt5-network
